# Generated by Django 4.2.4 on 2023-09-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
    ]
