# Generated by Django 4.2.4 on 2023-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_remove_author_books'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='autor.author'),
        ),
    ]
