# Generated by Django 4.2.4 on 2023-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
